### ISSUE TITLE
Local dataset in single .ad file or keep datastructure similar to non-local dataset?

### ISSUE THREAD

**Issue by grdw** [quintel/atlas#53]
@ChaelKruip showed me the initial idea for creating local datasets (which was a picture on a whiteboard - in a circular movement) which was drawn by @antw 

I remembered him telling me explicitly that a local dataset needs to be put in a single `.ad`-file.
But I was wondering what the reasoning behind that is? 

Wouldn't it be easier to just keep the data structure exactly the same to a non-local dataset?

**Comment by antw** [comment]
> that a local dataset needs to be put in a single .ad-file

"needs" is too strong a word. Please don't feel that you have to do it that way; you're free to explore alternatives (and indeed should). We only spent an hour discussing this, so the ideas we had were basic and didn't consider every possibility. In fact, I now think the idea I had would be quite fragile in the event that the structure of the graph changes (e.g. someone splits an existing node into two).

* One reason was that the full datasets we have today are based on CSVs exported from Excel. When researchers or modellers want to change something they change the Excel file, run a VBA script, and get new CSVs for all regions. I don't know the exact details, it's all magic to me. 😆

* I think it's also the case that there's a lot of data which you don't *need* to keep. For example, [this agriculture node](https://github.com/quintel/etsource/blob/066b583f09fe73c8244099522f40eed02bc2651b/nodes/agriculture/agriculture_final_demand_crude_oil.final_demand.ad) reduces about 20 different values from a CSV in a single demand. The idea was to just store the values that were mapped to nodes and edges.

* Chael had a pie-in-the-sky idea for a visual editor where you could click a node and adjust it's output shares, demands, efficiencies and so on, with the results being save to the AD file and factored in to the Refinery calculation step.

But since one of the main design goals is for this to be *maintainable*, perhaps storing a full dataset as CSVs is a viable approach? That seems fine if there are only two regional datasets; what if there are 100? (Is that a realistic possibility? – I don't know!)

It might be worth discussing this in more detail with Dennis, Alexander, and Joris to understand what makes the current approach hard to maintain, then you can design your approach accordingly.

You might also consider writing a short "project goals" document about what the project is intended to achieve: the goals, the problems it aims to solve, and the features it might have in version one, or in some future version a year or two from now. Then you and @ploh will be able to come up with a plan confident that you understand the problem, and with everyone on the same page.

**Comment by grdw** [comment]
> But since one of the main design goals is for this to be maintainable

That's the *idea* I'm having currently; that if you keep the local datastructure similar to the 'source' datatstructure (if you were to scale it - the first time - from another dataset) that it will remain maintainable purely due to it's consistency in workflow with other datasets. I don't want to - and I hope the rest of the data-people would agree with me - create a separate workflow for local datasets than non-local datasets. What does that even mean, a non-local dataset? Compared to the world; nl is also a local dataset. 😅 

> You might also consider writing a short "project goals" document about what the project is intended to achieve: the goals, the problems it aims to solve, and the features it might have in version one

We are already working on that 👍 😄
