### ISSUE TITLE
Importing graph 'bug'

### ISSUE THREAD

**Issue by grdw** [quintel/atlas#69]
When importing the graph, Refinery is stuck in an infinite loop when trying to calculate. It happens with these two slots:

````ruby
[
  #<Refinery::Slot (in, electricity) node=:industry_steel_hisarna_consumption_useable_heat>,
  #<Refinery::Slot (in, useable_heat) node=:industry_steel_hisarna_consumption_useable_heat>
], 

0/1 # demand sum of all edges (which is zero)
````

Now `industry_steel_hisarna_consumption_useable_heat` has three 'carriers' (or slots?) not two. It also has a coupling carrier which @ChaelKruip and @jorisberkhout explained to me what they were. Now I also noticed that when exporting the `graph.yml` for that perticalar node (`industry_steel_hisarna_consumption_useable_heat`) has a `cc_in` attribute. When importing what should I do with that `cc_in` attribute? Is that even the cause of the infinite loop? 

How do I properly debug this at all?

**Comment by grdw** [comment]
@ChaelKruip or @jorisberkhout I actually still forgot to ask the most basic question but what is `cc_in`, a demand or an efficiency? I'm still a bit unclear about that.

**Comment by ChaelKruip** [comment]
> @ChaelKruip or @jorisberkhout I actually still forgot to ask the most basic question but what is cc_in, a demand or an efficiency? I'm still a bit unclear about that.

I think it is a demand but @antw knows better. 

> How do I properly debug this at all?

Perhaps I'm grossly underestimating the problem here but...

STEP 1) I would go back to what we know works: the NL dataset for example. Before the graph is initialised, all values that are needed should be in memory right? So, the values for cc_in and cc_out should be set for NL as well. I think that the two hisarna nodes could be useful to look at given the issues you encounter.

STEP 2) Next, I would try to 'dump' the (unscaled) NL dataset into YML format and compare the values with those found in STEP 1. This way, you can check if all the needed values are still there in your new way of initialising. If not, it becomes a more-or-less-straightforward hunt for the calculation step where a value is not passed on to the next step right?

STEP 3) PROFIT!

**Comment by antw** [comment]
> I actually still forgot to ask the most basic question but what is cc_in, a demand or an efficiency?

It's a slot share (conversion). ETEngine has a "coupling carrier" used to communicate demands between two nodes without actually sending any energy. Refinery has no need for this, [so `coupling_carrier` is omitted from the Refinery graph](https://github.com/quintel/atlas/blob/1a67953fc974177bad9eb194750d4677b4b99880/lib/atlas/graph_builder.rb#L62). Since these slot conversions still need to be exported to ETEngine, they are saved as `cc_in` and `cc_out` attributes on the node, and [Atlas::Exporter](https://github.com/quintel/atlas/blob/1a67953fc974177bad9eb194750d4677b4b99880/lib/atlas/exporter.rb#L124-L127) looks for these attributes when exporting to ETE.

These attributes will not be responsible for the infinite loop.

> How do I properly debug this at all?

Use Ruby 2.3 which will give a usable stack trace (it'll print the stack out in reverse, but will at least show where the loop is occurring). I suspect [it will be here](https://github.com/quintel/refinery/blob/8cc81e91f2a7c7546f6c227208899eda8921a6e9/lib/refinery/slot.rb#L94).

If the full-size regions are calculating correctly, then it likely means the derived graph (from graph.yml) is either missing some data or - less likely - has some data which shouldn't be there.

I would create a graph.yml export of NL without any scaling, and compare the data stored in the graph [immediately prior to Refinery](https://github.com/quintel/atlas/blob/1a67953fc974177bad9eb194750d4677b4b99880/lib/atlas/runner.rb#L30) with the data from the full-size NL graph. Without any scaling, both should be identical. Any differences between the two might be a clue as to why one works and the other doesn't.

**Comment by grdw** [comment]
I found the problem. It had nothing to do with the `coupling_carrier`. The problem was that the `type` of the node was ignored. It was an `elastic` node but the import didn't saw it as such.
