### ISSUE TITLE
Should the graph.yml reflect on the values that are altered through the initializer inputs?

### ISSUE THREAD

**Issue by grdw** [quintel/atlas#74]
@ChaelKruip proposed an alternative idea for the initializer inputs and I want to test how feasible this is.

The current idea is to make initializer inputs behave like `user_values`. So:

````
[ Atlas::GraphDeserializer / Atlas::Runner]
          |
          V
[ Atlas::FullExporter ]
          |
          V
[ Load data from dumped MessagePack ]
          |
       [ ... ]
          |
          V
[ Overwrite inputs with initializer inputs ] [?]
````

As an expansion/extra-step to that idea @ChaelKruip proposed the following:

````
                  O B
                 / 
                / (A-B share: 0.5)
A (demand = 5) O 
                \ (A-C share: 0.5)
                 \ 
                  O C

````

Than this is the full-graph

````
                  O B (demand = 2.5)
                 / 
                / (A-B share: 0.5)
A (demand = 5) O 
                \ (A-C share: 0.5)
                 \ 
                  O C (demand = 2.5)

````

If a researcher than knows the demand of node/converter `B` and sets it to for example (10). This would work the same as the idea proposed above (as `user_values`).

````
                  O B (demand = 10)
                 / 
                / (A-B share: 0.5)
A (demand = 5) O 
                \ (A-C share: 0.5)
                 \ 
                  O C (demand = 2.5)

````

*The extra step*
Than the 'altered' sparse graph (if assuming the sparse graph will have the same starting points and edges) will look like:

````
                  O B
                 / 
                / (A-B share: 0.5)
A (demand = 20) O 
                \ (A-C share: 0.5)
                 \ 
                  O C

````

Should this be reflected in the `graph.yml`? Is that useful?

It would be useful - before running everything through ETEngine - to be able to check through `git` which numbers will change.

**Comment by ploh** [comment]
This definitely sounds like a desirable idea from a user standpoint.
Unfortunately, I believe it is not possible, since the initializer inputs are really gqueries with INPUT() statements and as such are executed in ETEngine, long after the graph is transformed from its Atlas representation to an internal ETE representation. Or am I not aware of some mechanism that would allow applying the inputs to the Atlas graph, @antw?

But maybe we can come up with a simple ETE graph export instead and then create a Rake task to use that to show the user a graph diff!?

**Comment by ChaelKruip** [comment]
> But maybe we can come up with a simple ETE graph export instead and then create a Rake task to use that to show the user a graph diff!?

I didn't want to steer you guys too much in one direction but that was what I was thinking as well 😄  If we could dump the graph (possibly reduced to sparse form) to some text-file after calculation with ETE that could do the trick. Downside of this approach is that this will only work if the graph is valid and can be calculated. So, this solution would not replace the need for some validation and error checking prior to loading the graph in ETE.

**Comment by ploh** [comment]
> possibly reduced to sparse form

I do not really see how this could be possible. We would have to "re-sparsify" the full graph, but how do you decide which edges may be omitted?

> Downside of this approach is that this will only work if the graph is valid and can be calculated

I am not sure I can follow that thought. If the initializer inputs make the graph invalid, we cannot really know that at any earlier step, can we? Or did you mean something else?

**Comment by ChaelKruip** [comment]
> I do not really see how this could be possible. We would have to "re-sparsify" the full graph, but how do you decide which edges may be omitted?

I think it should work if you select exactly the same edges and nodes as before. These were a sufficient set to unambiguously determine the full graph from, so they will still be. 

> I am not sure I can follow that thought. If the initializer inputs make the graph invalid, we cannot really know that at any earlier step, can we? Or did you mean something else?

As far as I understand there are two types of initializer inputs:
* values that override numbers currently stored in the region.ad file (like number of cars, number of old houses etc.)
* values that override the graph (demands, capacities, shares etc.)

The first class can create a graph that is non-computable from the start (a negative number of cars for example might lead to an error). Errors might be picked up in pre-ETE.

The second class will work with update statements similar to those currently used by sliders. We can only check their impact by running ETE.

Does that make sense @ploh @grdw @antw?

**Comment by ploh** [comment]
> I think it should work if you select exactly the same edges and nodes as before. These were a sufficient set to unambiguously determine the full graph from, so they will still be.

:+1: 

> Does that make sense

I think so, but I am not very familiar with how ETE works. So we better wait for @antw's answer :wink:

**Comment by ChaelKruip** [comment]
> What does this approach offer that the current proposal doesn't? That is: what new thing does it bring to the table?

Looking at https://github.com/quintel/internal/blob/master/planning/projects/local-datasets/planning.md I don't yet see any reference to functionality which allows the researcher/user to
* track changes in the graph/initial data using git diff-like methods
* seeing the impact of a (different) choice made in the "EXCEL-based-part of the process" on the graph apart from staring at the front-end or the graph layout (which is not alway insightful)
* debug the initialisation process prior to ETE choking on something (like rake debug)

I realise that the above is neither very clear or concrete but arguably very important in the process of creating and tweaking new local datasets.

> They are essentially like normal inputs with an extremely high priority and as such can alter anything a normal input can.

👍  thanks for clearing that up!

> In my mind, the "sparse graph" is the state of the graph immediately prior to being calculated by Refinery. Does the term have the same meaning in your examples? (i.e. the examples are Atlas+Refinery graphs, not ETEngine graphs).

Yes.

> How is it decided that the demand of [A] is set to 20?

By the researcher/user setting a key-value pair in the EXCEL analysis.

**Comment by antw** [comment]
> > How is it decided that the demand of [A] is set to 20?
>
> By the researcher/user setting a key-value pair in the EXCEL analysis.

Let me clarify: in the original example, `[A]` is set to a demand of 5, and via a share of 0.5 it is determined that the demand of `[B]` will be 2.5.

Then using an input, the a custom demand of 10.0 is set for `[B]`. *"Magically"* it is determined that the demand of `[A]` should therefore be 20.0. What is this magic step? How is it decided that the demand of `[A]` (and therefore also `[C]`) should increase?

> I don't yet see any reference to functionality which allows the researcher/user to
> [...]
> track changes in the graph/initial data using git diff-like methods

I agree better debugging and change-tracking would be nice. However, I disagree that `graph.yml` is the place to do this. `graph.yml` is supposed to represent a snapshot of the national scenario, optionally scaled down; it is otherwise intended to be immutable *except* in cases where you have to regenerate the YAML due to changes in the graph structure.

It is not intended to be edited, otherwise it would be impossible to distinguish between legitimate differences from the national dataset due to updates to the national scenario, and those changes which had been made by users; either by hand, or by copy/pasting a new graph from ETEngine.

The inputs are where the region-specific changes are made. @dennisschoenmakers considered it important that the differences between the original and derived dataset be a simple list of input keys and values, and exist in one place.

---

Would not a more desirable approach be to add a page to ETEngine where you could see a list of differences between the original `graph.yml` state and the current scenario?

**Comment by ploh** [comment]
> Would not a more desirable approach be to add a page to ETEngine where you could see a list of differences between the original graph.yml state and the current scenario?

That is what I was aiming at with the "simple ETE graph export". We definitely should not update the git-controlled graph.yml because of git-controlled initializer inputs.

**Comment by grdw** [comment]
>  What is this magic step? How is it decided that the demand of [A] (and therefore also [C]) should increase?

How does this currently work with `user_values`? Because this part is not clear to me. If you alter the demand of `B` to be 10. Than the `graph` in theory is 'incorrect'. I mean this: 

````
                  O B (demand = 10)
                 / 
                / (A-B share: 0.5)
A (demand = 5) O 
                \ (A-C share: 0.5)
                 \ 
                  O C (demand = 2.5)
````

... doesn't add up.

Because you change the demand of `B` you also need to alter either the shares or the other node demands in order for this to be a valid graph, right? (please correct if I'm wrong?)

**Comment by ChaelKruip** [comment]
> Would not a more desirable approach be to add a page to ETEngine where you could see a list of differences between the original graph.yml state and the current scenario?

👍

**Comment by antw** [comment]
> >  "Magically" it is determined that the demand of [A] should therefore be 20.0. What is this magic step?
>
> How does this currently work with user_values? Because this part is not clear to me. If you alter the demand of B to be 10. Than the graph in theory is 'incorrect'.

Indeed. I think this clarifies that you didn't intend to add this "magic" yourself, but expected ETEngine to do this for you already. Sorry to say that this is not the case.

Except when edges are `type=inversed_flexible` or `reversed=true`, the ETE graph is calculated from left-to-right. Which is to say that changing the demand of `[A]` will set the correct demand for `[B]`, but changing `[B]` will not affect `[A]`. Since this example intends to set a demand of 10 for `[B]` and `[C]` by setting `[A]` to 20, you would just set `[A]` to 20 and let ETEngine do the right thing for the other two nodes.

If you really wanted to set the demand using `[B]`, you would still set `[A]` but use the share of the edge between the two:

```ruby
# Pseudo-code:

a    = graph.node(:A)
b    = graph.node(:B)
edge = b.edges(:out).first  # The [A]<-[B] edge

# We want the output of the graph to have the demand of B to equal 10.
new_b_demand = 10.0

# Set the demand of [A]:
a.set(:demand, new_b_demand * edge.child_share)

# When computed, demand of [A] will be set to 20, and [B] and [C]
# will both be 10.
```

> How does this currently work with user_values?

The ETEngine graph goes through three phases:

1. **Initialization**: The graph is seeded with all the edge shares, all slot conversions, and preset demands for a small number of nodes (`[A]` is one such node in the example), and other information from the dataset.

    These preset values are never overwritten by ETEngine, they are considered to be authoritative. They *may* be overwritten in step 2 by inputs/user values.

    At this stage you a sparse graph in ETEngine.

    ```
                      O B (demand = nil)
                     /
                    / (A-B share: 0.5)
    A (demand = 5) O
                    \ (A-C share: 0.5)
                     \
                      O C (demand = nil)
    ```

2. **Updates**: Inputs are run, applying user values. This might be to change a seeded value (such as the shares of the edges), or to set a value which was previously blank to prevent ETEngine from calculating it automatically (such as setting the number_of_units for a power plant).

    You now have a sparse graph, plus values set with inputs.


    ```
                      O B (demand = nil)
                     /
                    / (A-B share: 0.3)
    A (demand = 5) O              ‾‾‾
                    \ (A-C share: 0.7)
                     \            ‾‾‾
                      O C (demand = nil)
    ```

3. **Calculation**: "Fill in the blanks"

    You now have a complete graph.

    ```
                      O B (demand = 1.5)
                     /              ‾‾‾
                    / (A-B share: 0.3)
    A (demand = 5) O
                    \ (A-C share: 0.7)
                     \
                      O C (demand = 3.5)
                                    ‾‾‾
    ```

**Comment by ploh** [comment]
@ChaelKruip Can we close this? The relevant idea can be followed in quintel/etengine#909

**Comment by ChaelKruip** [comment]
Closing.
