### ISSUE TITLE
Making the interconnector_capacity and possibly other attributes of the derived dataset ineditable

### ISSUE THREAD

**Issue by grdw** [quintel/atlas#80]
There's currently a problem - as far as I understand it - with the `interconnector_capacity` attribute. The thing is that this attribute is used several times to determine the demand of certain nodes. The demand of the nodes however are exported to the `graph.yml`. So when you change the `interconnector_capacity` of a local dataset in the `*.ad` file, your changes will not be visible. 

A solution I thought of would be to not have the `interconnector_capacity` inside of the `*.ad` file at all becuase it already implicitly lives inside of the `graph.yml`. 

Even stronger, I'd raise a warning/error if somebody defines it inside of the local dataset since adding it won't do anything to your graph.

**Comment by antw** [comment]
I'm not such a fan of this. `interconnector_capacity` is just an area attribute, and as such it *can* be used inside inputs and queries in ETEngine. Currently, it seems to be used [in only one place](https://github.com/quintel/etsource/blob/680b817ed3d83b9d319e4c2d8816d44fe088418b/inputs/flexibility/interconnectors/interconnectors_interconnector_capacity.ad#L7-L9).

This proposal would create two tiers of area attributes: those which may be accessed in ETEngine, and those which may not, and I'm not sure that's a good idea.

Perhaps we could instead add a spec in ETSource asserting that each derived dataset has matching `interconnector_capacity` and graph.yml values? If someone were to change the value in the `.ad` file, the spec will fail with a suitable warning.

**Comment by grdw** [comment]
> Currently, it seems to be used in only one place.

````bash
nodes/energy/energy_export_electricity.ad
16:~ typical_input_capacity = AREA(interconnector_capacity)

nodes/energy/energy_import_electricity.ad
14:~ electricity_output_capacity = AREA(interconnector_capacity)

nodes/energy/energy_interconnector_imported_electricity.converter.ad
17:~ electricity_output_capacity = AREA(interconnector_capacity)
````

I found them used in 3 loose nodes aswell. My thought would be that those attributes like `electricty_output_capacity` and `typical_input_capacity` would be than editable through an initializer input? 

This item however, sparkled some discussion with @ChaelKruip and @jorisberkhout because this might be something bigger than just this technical problem 😅

**Comment by ploh** [comment]
> > A solution I thought of would be to not have the `interconnector_capacity` inside of the `*.ad` file at all becuase it already implicitly lives inside of the `graph.yml`. 

> I'm not such a fan of this. `interconnector_capacity` is just an area attribute, and as such it *can* be used inside inputs and queries in ETEngine.

Exactly, and that is why we may not simply delete it from the area attributes (in fact the dataset will not be valid then, because of this: `validates :interconnector_capacity, numericality: true`).

> Perhaps we could instead add a spec in ETSource asserting that each derived dataset has matching `interconnector_capacity` and graph.yml values? If someone were to change the value in the `.ad` file, the spec will fail with a suitable warning.

That sounds like a viable idea for the `interconnector_capacity`, but... also a bit like a hack, since the `interconnector_capacity` does not directly live in the graph.yml, but only values derived from it, e.g.
```
etsource/nodes/energy/energy_import_electricity.ad:

~ electricity_output_capacity = AREA(interconnector_capacity)
```
Now in this case it is easy to check the derived value, but that might not be so in general.

Concluding, the problem goes beyond the `interconnector_capacity` in general: Whenever an area attribute is used to set a dynamic attribute of a node / edge, we have to keep the derived dynamic attribute which is persisted in graph.yml in sync with the area attribute which may be changed in the derived_dataset.ad file.
Hence, I had another idea: We could remove all the area attributes from the derived_dataset.rb file and persist them in the graph.yml instead. At runtime we make "virtual attributes" for the dataset (and by that also for `AREA()` gqueries) that delegate to the graph.yml values.

Further thinking about it... I have an idea that combines @antw's and my idea from above:
1. Persist the area attributes in the graph.yml when creating the derived dataset
1. Create a spec in etsource that
   1. determines which area attributes are used in nodes / edges dynamic attributes - only those are relevant here, since occurrences in inputs, chart gqueries etc. are not persisted in graph.yml.
   1. checks that these used attributes are equal in derived_dataset.rb and graph.yml

@antw @grdw What do you think?

**Comment by ploh** [comment]
> My thought would be that those attributes like electricty_output_capacity and typical_input_capacity would be than editable through an initializer input?

So maybe we should completely forbid directly manipulating the area attributes and the user can do this with initializer inputs? That would be my proposed solution from above (without the combination with Anthonys idea).

@ChaelKruip @jorisberkhout What do you think about that?

**Comment by ChaelKruip** [comment]
I think that the `interconnector_capacity` is in the wrong place (area.ad) at the moment. 

We have a Principle (with capital p) that technical node attributes are **not** area-specific. For the exceptions (`full_load_hours` and `demands`), we have area-specific CSV files such as [this one](https://github.com/quintel/etsource/blob/master/datasets/nl/central_producers.csv).

The area.ad file keeps all area-specific values which are **not related to the graph** such as the `number_of_cars`. 

In my view, the `interconnector_capacity` is an area-specific value which is also related to graph-nodes. Therefore, I think the logical place for it would be in its own private CSV file. 

This CSV file will be written with the others when the researcher exports the area-analysis Excel thing using VBA or scaled by a rake task (whichever we currently do with these area-dependent CSVs).

In that way, there is no inconsistency, the researcher can change the value (in the analysis) and we don't need any checks right?

**Comment by ChaelKruip** [comment]
Including @jorisberkhout

**Comment by ploh** [comment]
> In my view, the interconnector_capacity is an area-specific value which is also related to graph-nodes. Therefore, I think the logical place for it would be in its own private CSV file.

:+1: 

> In that way, there is no inconsistency, the researcher can change the value (in the analysis) and we don't need any checks right?

Just be aware of the [input which uses it](https://github.com/quintel/etsource/blob/3b2b3c09ff15b859fb64bf27214212f711c0fbe7/inputs/flexibility/interconnectors/interconnectors_interconnector_capacity.ad). I am not sure whether this will still work with a special `INTERCONNECTOR_CAPACITY()` instead of `AREA(interconnector_capacity)`.

So far, all the CSV files are either only used by ETEngine or only used by Atlas/Refinery, but never by both. Why is this important?
Take e.g. the [primary_production.csv](https://github.com/quintel/etsource/blob/9e497c279596ab1f2157180b675e6e0759fdb95b/datasets/nl/primary_production.csv), this is only used for dynamic node attributes, i.e. after we created a graph.yml for a derived dataset, we do not need this file any longer - so we do not create it for a derived dataset.
The `load_profiles` on the other hand are only used in ETEngine, so we create these files for a derived dataset (and the user may edit them). If they were _also_ used to build the graph, we would have to worry about inconsistencies again.

**Comment by ChaelKruip** [comment]
> Just be aware of the input which uses it. I am not sure whether this will still work with a special INTERCONNECTOR_CAPACITY() instead of AREA(interconnector_capacity).

I think we can query the graph to get the same info into the input statement.

> So far, all the CSV files are either only used by ETEngine or only used by Atlas/Refinery, but never by both. Why is this important?
Take e.g. the primary_production.csv, this is only used for dynamic node attributes, i.e. after we created a graph.yml for a derived dataset, we do not need this file any longer - so we do not create it for a derived dataset.
The load_profiles on the other hand are only used in ETEngine, so we create these files for a derived dataset (and the user may edit them). If they were also used to build the graph, we would have to worry about inconsistencies again.

@antw can you answer this?

**Comment by antw** [comment]
> @antw can you answer this?

I don't see a question. :confused: I think @ploh is correctly stating that CSV files tend to be used either to build the Atlas+Refinery graph, or as support files in ETEngine, but not both.

* The former do not need to be included as part of a derived region, as the serialized "graph.yml" contains all of the values which are computed from these CSVs: everything needed to build the graph.
* The latter are still included with a derived region – scaled down as needed – so that ETEngine can use them.

A problem would emerge if a new type of CSV file were used in both Atlas+Refinery and ETEngine, since the CSV would have to be included with the derived region. This means that someone might hand-edit this CSV expecting the graph.yml to also change, and this is not the case: you would have a graph.yml and CSV which are no longer consistent with one another. I'm not sure how to resolve this.

**Comment by ploh** [comment]
> I'm not sure how to resolve this.

But I am :stuck_out_tongue_winking_eye: :
In this case we are lucky, because the only place where the `interconnector_capacity` is used directly in ETEngine is [this input](https://github.com/quintel/etsource/blob/3b2b3c09ff15b859fb64bf27214212f711c0fbe7/inputs/flexibility/interconnectors/interconnectors_interconnector_capacity.ad). And there, if my understanding of GQL is correct, we can simply replace
```
present:AREA(interconnector_capacity)
```
with

```
present:V(energy_export_electricity, typical_input_capacity)
```

Then, the `interconnector_capacity` will only be used by Atlas+Refinery and therefore the new CSV file does not need to be included in a derived region.

**Comment by antw** [comment]
> And there, if my understanding of GQL is correct, we can simply replace [...] Then, the interconnector_capacity will only be used by Atlas+Refinery and therefore the new CSV file does not need to be included in a derived region.

That's right. :+1:

> I'm not sure how to resolve this.

I meant more generally that future CSVs might not be so easy to solve. Particularly in cases where [an attribute is not a one-to-one map with a CSV value](https://github.com/quintel/etsource/blob/680b817ed3d83b9d319e4c2d8816d44fe088418b/nodes/agriculture/agriculture_final_demand_network_gas.final_demand.ad#L6-L8) there will be no way for ETE to simply query the original value: the CSV will have to be there.

Perhaps we should not worry about that for now. We've gone this long without a CSV being used in both places; it might never come up.

**Comment by ploh** [comment]
> Perhaps we should not worry about that for now. We've gone this long without a CSV being used in both places; it might never come up.

:+1:

**Comment by grdw** [comment]
This is no longer relevant with the auto-scaling of the graph.
