### ISSUE TITLE
Derived datasets: Relation between initializer inputs and normal inputs

### ISSUE THREAD

**Issue by ploh** [quintel/atlas#85]
Should init. inputs be a separate class `InitializerInput` or should we continue using `Input`?
And if separate, then should `InitializerInput` and `Input` share a common base class? Maybe that would be called `Input` then and what is now `Input` becomes `UserInput`!?

There was some discussion about this [in another issue](https://github.com/quintel/etmodel/issues/2324#issuecomment-273460352) already

**Comment by antw** [comment]
> Should init. inputs be a separate class InitializerInput or should we continue using Input?

Originally I thought "yes", and although I still lean towards that I could be convinced otherwise. 😆 

When @dennisschoenmakers and I put the original "simplified" plan together, the expectation was the researchers and modellers would create all-new (initializer) inputs for the purpose of customising derived datasets.

I think it depends on how modellers will actually use derived datasets. Is there a lot of overlap between inputs which already exist, and things they'd like to set with initializer inputs? If this is the case, I still prefer the idea to keep them separate, [but add a `delegates_to` attribute](https://github.com/quintel/etmodel/issues/2324#issuecomment-273486023) which allows the reuse of a normal input. At least that would be explicit with no risk of confusing an initializer input for a user input.

> And if separate, then should InitializerInput and Input share a common base class? Maybe that would be called Input then and what is now Input becomes UserInput!?

My opinion is *probably* no.

* There's not much commonality between the two except for `query` and (maybe) `update_type` attributes.

* User inputs and initializer inputs would have the same unique key constraint: in fact it might be desireable for an init. input to have the same name as a user input.

* It pollutes input file names with "something.user.ad": everyone who hand-creates an input will have to remember to include the ".user" part or things might break in unpredictable ways.

If there are other similarities between the two classes I'm not considering, we might add the common stuff to a module which would be included in `Input` and `InitializerInput`.

---

Including @ChaelKruip and @dennisschoenmakers

**Comment by ploh** [comment]
cc @grdw

**Comment by ChaelKruip** [comment]
My opinion is that we 
* should start with a fresh set of initialiser inputs (perhaps having the word "initialiser" in the name to distinguish them from the rest)
* put them in their own directory (the initialiser_input directory seems fine)
* design them to be the 'necessary and complete' set of inputs to change anything a researcher would want to change
* write them in such a way they do not depend on the end-year (so no %/year type update statements)

**Comment by ploh** [comment]
So we create a new class `InitializerInput` which does not have to much in common with the existing `Input`!

For the set of init. inputs to create, refer to quintel/etsource#1212

**Comment by ploh** [comment]
Closed by #86 really
