### ISSUE TITLE
Adding a new node to ETsource causes an error with a local dataset

### ISSUE THREAD

**Issue by grdw** [quintel/atlas#96]
This is more of a fundamental problem that causes this bug to appear. On the one hand a 'local graph' should be unaffected by the changes of the graph and live independently of the base dataset (which is the whole reason we persued this project) (in this case `nl`). However there should only be a single energy graph with all of it's nodes and edges to keep the front-ends consistent (which is the basic principle).

These two things are a bit mutual exclusive and cause quite the dilemma. I think what would be best (process wise) is that the `graph.yml` contains the graph as it was and won't update until a researcher explicitly does so (by a yet to be defined rake task, also some initializer inputs might become deprecated and needs changes etc.). This would imply that - when the graph expands with a new node and the front-end expands with a new slider - that it wouldn't work for that perticular dataset (or?) for a moment of time. 

---
---

Right now there's an actual bug with the following:

Assume a graph with two nodes:

```
A -> B 
```

When this is scaled a snapshot is made in the `graph.yml`. Than the `graph` updates:

```
A -> B -> C
```

[`GraphDeserializer`](https://github.com/quintel/atlas/blob/master/lib/atlas/graph_deserializer.rb) complains about the new node `C` since it's not present in the `graph.yml`. It starts of with the [existing structure](https://github.com/quintel/atlas/blob/master/lib/atlas/graph_deserializer.rb#L31) of the `nodes` and `edges` of `etsource`. (It should or shouldn't depending on the outcome of the discussion above, reject all the new nodes and edges).

---
---

But before resolving the bug it might be nice to know what to actually do about it in a broader sense. I also recall that there has been discussion about this before. If I find it, I'll post it in this issue.

Including @antw @jorisberkhout @DorinevanderVlies @ChaelKruip

**Comment by DorinevanderVlies** [comment]
> I think what would be best (process wise) is that the graph.yml contains the graph as it was and won't update until a researcher explicitly does so (by a yet to be defined rake task, also some initializer inputs might become deprecated and needs changes etc.). 

I am not in favour of the idea of multiple graphs with their own interface living at the same time. I think, when the graph is changed, the local datasets should be changed accordingly.

The disadvantage of this solution is that is adds an extra step to the process of making changes to the graph. And that for this step a developer is required..

In this cases, where we're adding a node with present demand 0 which won't cause any issues. @grdw are you expecting difficulties when more elaborate changes are mode to the graph?

**Comment by DorinevanderVlies** [comment]
@grdw what would be a good process? That we implement he changes locally and inform you when that's done?

**Comment by grdw** [comment]
> I am not in favour of the idea of multiple graphs with their own interface living at the same time. I think, when the graph is changed, the local datasets should be changed accordingly.

In this case, yes. A single node with a demand of 0 is not that massive of a change.

> @grdw are you expecting difficulties when more elaborate changes are made to the graph?

No, if you'd like to keep all graphs similar than I'd expect no problems other than that the amount of initializer inputs of the dataset might not be sufficient and / or other data-modelling problems.

> @grdw what would be a good process? That we implement he changes locally and inform you when that's done?

In all honesty: no. For now: sure, but for the future: please no. I'm going to redirect this question to you and ask what you'd think a nice workflow will be. My personal solution to this problem would be this:

1. I fix the bug / error for when adding a new node for a local dataset
2. I add a rake task with which you can manually update a local dataset's graph.

The reason I think step 2 would be included is because it can prevent a lot of 'automatic' harm to scenario's which was the main reason that the local datasets project was called to life. 

The workflow would be: 

1. Add a new node
2. Local datasets / scenarios should still work
3. If necessary update the graph of the local dataset
4. Thoroughly test if the changes to the graph don't cause any to severe changes

**Comment by antw** [comment]
> I fix the bug / error for when adding a new node for a local dataset

I'm curious what this fix might entail, because in my mind a derived dataset "failing" in this way is not a bug but a feature. Obviously it is an *annoying* feature, but I think it's correct for missing data to be a fatal error.

> Assume a graph with two nodes:
> 
> `A -> B ` when this is scaled a snapshot is made in the graph.yml.  
> Than the graph updates: `A -> B -> C`

Putting this graph back through Refinery would certainly result in it correcting the error because it is easy to figure out that the demand of new node `[C]` should be equal to that of `[B]`. However, as changes to the graph become more substantial – such as nodes with multiple slots/carriers, or several edges – Refinery may not be able to produce a new valid graph without requiring more information. For example, let's say we have a graph like this:

```
                 <- [cars using electricity]
[transport_cars] <- [cars using gasoline]
                 <- [cars using hydrogen]
                 <- ...
```

Now we choose to split cars using electricity into low-capacity "conventional" EVs and those which can charge at a higher-capacity:

```
                 <- [cars using electricity, low capacity]
                 <- [cars using electricity, high capacity]
[transport_cars] <- [cars using gasoline]
                 <- [cars using hydrogen]
                 <- ...
```

There's no way for Refinery to automatically fix this, because it cannot know the share of low and high capacity cars without the user providing more information.

This is why `graph.yml` is not allowed to be hand-edited: so that you could easily throw it away and generate a new one whenever the graph *structure* changes. Simpler changes (to demands, shares, efficiencies, etc) don't change the graph structure, and so allow you to continue using the same `graph.yml`. Settings which differ from the full-region and are important to a derived dataset – such as disabling industry, or setting a custom demand – are specified in initializer inputs so that those customisations will persist after a `graph.yml` update.

> Thoroughly test if the changes to the graph don't cause any to severe changes

Agree very much with this. A script which takes the old and new `graph.yml` files as inputs and reports on any significant changes would allow researchers to more easily see what has changed.

**Comment by grdw** [comment]
> I'm curious what this fix might entail

This is the bug:

![screen shot 2017-05-19 at 10 03 31](https://cloud.githubusercontent.com/assets/2676542/26238691/73af7c16-3c7a-11e7-876c-809f5a6e4fb9.png)

In technical terms what I saw happening was a "undefined method `each_pair` for nilClass" [here](https://github.com/quintel/atlas/blob/master/lib/atlas/graph_deserializer.rb#L36) (I guess). So my fix would be to make sure that `node_attributes` always returns a Hash. And that's it actually. :) 

It might still be - after the above fix - as you say ...

> There's no way for Refinery to automatically fix this, because it cannot know the share of low and high capacity cars without the user providing more information.

.. that this can happen. But that would display a different error message I guess.

**Comment by grdw** [comment]
> But that would display a different error message I guess.

And this is the actual useful error message you'd want to see:

![screen shot 2017-05-19 at 10 10 56](https://cloud.githubusercontent.com/assets/2676542/26238945/803a72b4-3c7b-11e7-98a1-5f025701a178.png)

**Comment by antw** [comment]
> This is the bug:

Oh I see, it's an actual bug/exception. Fair enough then. 😆 

Missing data is the sort of thing we'd normally validate in the ETSource or Atlas specs: this way the ETSource specs will fail and immediately alert us something is wrong (and that the error is with data rather than code). If someone was to add a new node or edge, the specs for a derived dataset should fail due to missing data. Something like:

```ruby
module Atlas
  class Dataset::Derived < Dataset
    validates_with SerializedGraphvalidator
    # ...
  end

  class SerializedGraphValidator < ActiveModel::Validator
    def validate(record)
      return false unless validate_file_exists(record)

      validate_nodes(record)
      validate_slots(record)
      validate_edges(record)
    end

    private

    def validate_file_exists(record)
      # Assert that graph.yml exists
    end

    def validate_nodes(record)
      # Assert that for every Atlas::Node, graph.yml has node data
      # Assert that graph.yml does not specify nodes which don't exist.
    end

    def validate_slots(record)
      # For each Atlas::Node, assert that graph.yml has slot data for each
      # Node#in_slot and Node#out_slot
      #
      # Assert that that the graph.yml does not have any slots which don't exist
      # in the Node (they've been deleted?). Possibly slots whose carrier is
      # :coupling_carrier will have to be skipped.
    end

    def validate_edges(record)
      # Assert that for every Atlas::Edge, graph.yml has node data.
      # Assert that graph.yml does not specify edges which don't exist.
    end
  end
end
```

I'm happy to take care of this if you're busy with other things. Just let me know. :smiley:

**Comment by grdw** [comment]
> I'm happy to take care of this if you're busy with other things

I'm fine with picking this up. 👍  Thanks for the suggestion though. Seeing your answer does give me an idea. How discriptive can the actual error message be? I was thinking, a missing node or edge or slot automatically points to the fact that somebody added a node. With the idea in mind to update the graph with a yet to be written rake task, we could specify in the error message:


"Node x is missing from the graph snapshot for derived dataset x. Please update the graph snapshot with the following script: 

`rake update_graph DATASET=x`"

**Comment by grdw** [comment]
Fixed as specified with: 

- Atlas changes: https://github.com/quintel/atlas/pull/98
- ETSource rake task: https://github.com/quintel/etsource/pull/1276
